# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8657781e74b12d1358c1bcf7ba1a622a0bc7eafc32e2f8fe81bbb87f86439acae12e635e5b8aa1c79cfcad2da5bd9224d8a960f866221166ed84fc19b2ba5c1

test:
  secret_key_base: d75e311658732884e7d5257dba7c3f64664f8a0cd3ce3b6da06a2efec6248a12caf09f4a1c1474ec9e7e7d0627847b82813ee83130b7085a607a1fa51fffcbe7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
